Infiziert90/ChatTwo

.editorconfig
ChatTwo/Chunk.cs
ChatTwo/Message.cs
ChatTwo/PayloadHandler.cs
ChatTwo/Resources/Language.Designer.cs
ChatTwo/Resources/Language.resx
ChatTwo/Store.cs
ChatTwo/Util/ChunkUtil.cs
ChatTwo/Util/ImGuiUtil.cs
ChatTwo/Util/Payloads.cs

Adds a parsing step when constructing `Message` objects that scans the message content for anything that looks URL-like, and inserts new `TextChunk`s into the message content with a URIPayload set.
Hovering over a URL shows an on-hover effect. Clicking a URL opens it in the default browser. Right clicking shows the hostname, with an option to open and an option to copy the URL to the clipboard.
This runs a regex on each received message once to find URLs. Since messages are cached in memory and in the database, the regex doesn't get run again when reloading the plugin.
The regex is a bit quirky but I think it's a good compromise for detecting most URLs. It'll match:
- any URL with a scheme (regardless of TLD): `https://anything.anything.blah/asda`
- any dot separated string starting with …

feat: clickable URLs in chat log

---

ChatTwo/Code/ChatType.cs
ChatTwo/Code/ChatTypeExt.cs
ChatTwo/Code/InputChannel.cs
ChatTwo/Code/InputChannelExt.cs
ChatTwo/GameFunctions/Chat.cs
ChatTwo/PayloadHandler.cs
ChatTwo/Resources/Language.Designer.cs
ChatTwo/Resources/Language.resx
ChatTwo/Ui/ChatLogWindow.cs

Adds ExtraChat Linkshell channels to tab input channel selector. These are only by index, not by channel name due to limitations in the ExtraChat IPC API (tab channel will only show `ECLS [X]` instead of `ECLS [X]: Linkshell Name`).
Because we can't get a map from linkshell number to linkshell name (AFAIK we can only get "ID" to name) from the ExtraChat plugin we show all numbers from 1 through 8 in the selectors. If people don't use the ExtraChat plugin or aren't in any EC linkshells, these options won't appear in the channel selector.
Adds ExtraChat Linkshell channels to the channel selector in the chat log window. As these aren't real channels in-game, these are handled by just sending the corresponding `/eclX` command which causes ExtraChat to set a channel override (which includes …

feat: allow tab input channel to be set to ExtraChat

---

ChatTwo/Code/ChatTypeExt.cs
ChatTwo/Ui/SettingsTabs/ChatColours.cs

fix: avoid warning logs about extrachat

---

ChatTwo/Resources/Language.Designer.cs
ChatTwo/Resources/Language.resx
ChatTwo/Store.cs
ChatTwo/Ui/Settings.cs
ChatTwo/Ui/SettingsTabs/Database.cs
ChatTwo/Util/ImGuiUtil.cs
ChatTwo/Util/StringUtil.cs

Shows path to database (click to copy), database size, database log size, message count.
Also adds a Ctrl+Shift button to wipe the database permanently. This is performed by clearing the Messages collection and then rebuilding the database, which brings it down to around 48KB on my machine (even with many messages).

feat: add database details section to settings

---

ChatTwo/Configuration.cs
ChatTwo/Resources/Language.Designer.cs
ChatTwo/Resources/Language.nl.resx
ChatTwo/Resources/Language.resx
ChatTwo/Ui/ChatLogWindow.cs
ChatTwo/Ui/SettingsTabs/Display.cs
ChatTwo/Util/ImGuiUtil.cs

Adds an option to limit the amount of lines being rendered in the chat frame.
Default to 10k to keep it similar to the max database size right now.

Add option to limit the amount of shown log lines

---

ChatTwo.Tests/LegacyMessageImporterTest.cs
ChatTwo.Tests/MessageStoreTest.cs
ChatTwo/ChatTwo.csproj
ChatTwo/Chunk.cs
ChatTwo/Code/ChatCode.cs
ChatTwo/LegacyMessageImporter.cs
ChatTwo/Message.cs
ChatTwo/MessageManager.cs
ChatTwo/Plugin.cs
ChatTwo/Ui/LegacyMesasgeImporterWindow.cs
ChatTwo/packages.lock.json

- Adds `LegacyMessageImporterEligibility` which checks eligibility of importing and returns a status
- Adds `LegacyMessageImporter` which handles the importing in a safe way, failed messages get logged and counted. Exposes progress information for the UI.
- Adds `LegacyMessageImporterWindow` which checks eligibility on startup, notifies the user and shows them current status.
- Add button to database settings page
- UI needs to be tidied up, it's very bare bones and hardly functional currently
- Strings into language resources? (maybe not since this is temporary)
- Canceling the ongoing import job should ask the thread to stop (using some condition variable) and wait for the thread to return (probably using another condition variable)
- Manual testing
- Does running the migration twice …

feat: add LiteDB => Sqlite importer

---

ChatTwo/Plugin.cs
ChatTwo/Util/AutoTranslate.cs

The Race, Tribe and BuddyAction sheets were skipped as the default behavior was to include rows from `0..^0` if no range was specified in the Completion sheet. That range would usually include everything, but since the ranges were iterated over as integers there is no "last" index so `^0` equals zero.
Also preloads the AutoTranslate cache on plugin load in a new thread to avoid a hitch when sending the first message. This behavior is disabled in DEBUG builds to make profiling easier.
Pasting `<at:52,4> <at:53,7> <at:58,4>` into dev and current release:

fix: add Races, Clans and Companion Actions to auto-translate

---

ChatTwo/GameFunctions/GameFunctions.cs
ChatTwo/PayloadHandler.cs

I was looking into event item handling and I noticed the default game was setting the `0x118` offset byte to 8 instead of 1 for these items. By doing the same in Chat2, it seems these items are now handled as expected (at least from my testing).

Handle event items by checking item kind

---

ChatTwo/GameFunctions/GameFunctions.cs

I noticed an issue where item count tooltip lines from Allagan Tools were being added twice to Chat2 linked item tooltips and was able to track down the cause to the way item tooltips are being hidden on mouse out. Currently we just hide the tooltip, but Dalamud has a `HandleItemOut` hook which isn't called when we do this. This hook is used by Allagan Tools to track the last hovered item, and not calling it was causing the issue.
I found that by sending an artificial close event to AgentItemDetail we are able to hide the tooltip without skipping that hook. We also don't need to clean up the struct in that case since the event handler also does that part (though I left it in as a fallback, maybe unnecessarily).

Close item tooltip with event to support Dalamud HandleItemOut hook

---

ChatTwo/Code/ChatCode.cs
ChatTwo/LegacyMessageImporter.cs
ChatTwo/Message.cs
ChatTwo/MessageManager.cs
ChatTwo/Plugin.cs
ChatTwo/Ui/ChatLogWindow.cs
ChatTwo/Ui/LegacyMessageImporterWindow.cs
ChatTwo/Ui/Settings.cs
ChatTwo/Ui/SettingsTabs/Database.cs

Changes almost every `FilterAllTabs()` call to `FilterAllTabsAsync()`, which uses a thread.
Changes incoming message processing to push messages onto a queue which gets processed in a thread in order. Removed accidental double `MessageStore.UpsertMessage()` call.
If "Save battle messages in database" is disabled, "error" messages will no longer be saved. This avoids a bunch of database writes when macros fail.

chore: use threads for DB reading and writing

---

ChatTwo/Message.cs
ChatTwo/Ui/ChatLogWindow.cs

- Avoids extra `""` text chunks after message parsing if the last chunk was an emote
- Adds an empty string after emote chunks if they're the last item in the chunk list so the ImGui newline code handles everything properly

fix: ensure newlines when rendering emotes

---

ChatTwo/MessageManager.cs
ChatTwo/Util/ExtraPayload.cs
ChatTwo/Util/GlobalParametersCache.cs

- Add back `PendingMesasage` which contains raw message details
- Adds `GlobalParametersCache` which stores data about chat color codes in a cache so they can be accessed outside of the main thread
- This gets refreshed every time we receive a message
- Changes the `ChatMessage` handler to always wait a tick before enqueuing messages, even if we don't need to get the Content ID to avoid processing messages out of order

chore: move message processing to thread again

---

ChatTwo/Chunk.cs
ChatTwo/Ui/ChatLogWindow.cs

- Fixes TextChunks with null content from crashing chat log (thanks `@ashekahkol` for reporting)
- Prevents TextChunks fwith null content from being written, they will now be replaced with `""` (thanks `@ashekahkol` for reporting)
- Fixes messages being rendered on the same line as the previous message (thanks `@amper` for reporting)
- Fixes messages being clipped off at the start in modern view (thanks `@nebuchadnezzer2` for reporting)
The last two fixes are solved with a hacky fix, but it seems to work from my testing.

fix: various bug fixes

---

ChatTwo/MessageManager.cs
ChatTwo/MessageStore.cs
ChatTwo/Util/ChunkUtil.cs

- Removes URIPayload parsing in ChunkUtil, as it will never originate from the game
- This was causing message receive failures
- Adds `Deleted` column to messages table, Deleted messages won't be retrieved when loading history
- If messages fail to parse, they are marked as deleted (but not actually deleted)

fix: avoid loading failed parse messages again

---

ChatTwo/Util/AutoTranslate.cs

The last row wasn't being included when adding some auto-translate categories, such as Race (so you couldn't pick Viera).
Closes #57

fix: add last row from some auto-translate categories

---

ChatTwo/Configuration.cs

`0` means lock instantly, or fail if lock is currently held by something else.

fix: use infinite lock timeout on write thread

---

ChatTwo/Configuration.cs
ChatTwo/Resources/Language.Designer.cs
ChatTwo/Resources/Language.resx
ChatTwo/Ui/ChatLogWindow.cs
ChatTwo/Ui/SettingsTabs/ChatLog.cs
ChatTwo/Util/ImGuiUtil.cs

Adds a close button beside the settings button in the chat log. Some changes to `ImGuiUtil.IconButton()` were required to ensure the sizes of the buttons matched up.

feat: add close button to chat log

---

ChatTwo/Configuration.cs
ChatTwo/GameFunctions/Chat.cs
ChatTwo/Resources/Language.Designer.cs
ChatTwo/Resources/Language.resx
ChatTwo/Ui/ChatLogWindow.cs
ChatTwo/Ui/SettingsTabs/Display.cs

After not receiving a message for X seconds (configurable) in the current tab or any tab with unread mode enabled, the chat will be hidden. Focus can be returned with return or slash as usual.
Having input focus or hovering the mouse over the chat window "bumps" it every frame.
Also fixes a bug that prevented focus from being restored to tabs with input disabled. The chat window will now be correctly brought back but the activated event won't be fully processed.
Thanks @aurieh
https://github.com/Infiziert90/ChatTwo/assets/11241812/5a2b4f8a-99e6-4a67-8ae8-b154b7cab9a6
Relates to #80

feat: add autohide after inactivity

---

ChatTwo/GameFunctions/Chat.cs
ChatTwo/GameFunctions/KeybindManager.cs
ChatTwo/Ui/ChatLogWindow.cs

Prevents switching channels to a non-existent linkshell index (for both regular linkshells and cross-world linkshells). ExtraChat linkshells are already validated separately.
Prevents ChatLogWindow Draw failures from causing ChatTwo to grab input focus each frame if the exception occurs during an Activate event.

fix: avoid switching to non-existent linkshell idx

---

ChatTwo/Configuration.cs
ChatTwo/GameFunctions/KeybindManager.cs
ChatTwo/Message.cs
ChatTwo/Resources/Language.Designer.cs
ChatTwo/Resources/Language.resx
ChatTwo/Ui/ChatLogWindow.cs
ChatTwo/Ui/Popout.cs
ChatTwo/Ui/SettingsTabs/Display.cs
ChatTwo/Ui/SettingsTabs/Tabs.cs
ChatTwo/Util/ImGuiUtil.cs
ChatTwo/Util/TabsUtil.cs

- Adds new setting "Enable inactivity hide during battle" (default: true) which determines whether autohide should apply during battle (thanks @aurieh)
- Adds new setting "Chat channels considered for activity" which allows customizing which channels incoming messages must match to "bump" the inactivity timer
- Adds new per-tab setting "Unhide the chat window on activity" to configure whether it will be considered for "bumping" the inactivity timer when receiving messages that match the new channel filter. Note that the foreground tab is currently always considered.
- Extends autohide code to apply to poped-out tabs as well. Each popout window has its own inactivity timer, but focusing the main window will restore all popped out windows.

feat: autohide improvements

---

ChatTwo/GameFunctions/Chat.cs
ChatTwo/GameFunctions/KeybindManager.cs
ChatTwo/Ui/ChatLogWindow.cs

- Avoids overriding modifiers after leaving a vanilla text box. This would prevent you from holding e.g. Ctrl between multiple vanilla text boxes.
- Reworks linkshell rotation code to fix issues with LS number gaps causing linkshell rotation to not function.

fix: various keybind fixes (modifiers and linkshells)

---

ChatTwo/Http/static/start.css
ChatTwo/Http/static/start.js

The first cleans up the `pointer-events` property on the (locked) channel button in a nicer way. The second change adds some more explicit CSS to emotes to hopefully get them to show up properly on (mobile) Safari.

Two small web frontend changes

---

ChatTwo/Ui/ChatLogWindow.cs

Heyo,
I added a functionallity to allow the user to cycle through auto complete options using the tab key in the way the base game does. Apologies for the hacky solution, this was due to the callback not recognizing the tab input via the `data->EventKey`. I imagine this is probably doable using the `ImGuiInputTextFlags.AllowTabInput` flag and culling the additional tab input from the buffer but im a bit out of my depth when it comes to C# let alone unsafe code in the language. 
I understand this isn't an ideal solution so please let me know if you have any concerns 😄 
Cheers

Added tab support to auto completion box

---

ChatTwo/GameFunctions/Chat.cs
ChatTwo/Util/AutoTranslate.cs

`WorkingRawRow` shouldn't be needed, but using raw row directly like https://github.com/goatcorp/dalamud-docs/blob/main/docs/versions/v11/lumina.md#reading-columns says doesn't work
For some reason the `LookupTable` field now contains some values as macros instead of just string, converting that back is kinda ugly like that, but it works.
The unexpected macro thing is just to ensure there will be an error in the log if they start using other macros in that field
Also fixes 2 minor unrelated issues I found during testing, when I did the whole api 11 update for myself.

Update AutoTranslate for API 11
